baseurl = "https://samgraymedia.github.io/"
relativeurls = true
languageCode = "en-us"
title = "im5am"
theme = "H-C-P-T"
googleAnalytics = "UA-96947489-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/samgraymedia"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/samgray75"

[params]
    description = "This is me. I am Sam"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
